---
title: "Data Unification"
author: "David Dominguez - A01570975"
date: "2024-04-10"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_download: TRUE
    theme: cosmo
---

# Creating the Necessary Databases

## Libraries Necessary
```{r message=FALSE, warning=FALSE}
library(imputeTS) # Rellenar datos faltantes
library(xts) # Manipulación de series temporales
library(zoo) # Sistemas de series temporales
library(tseries) # Análisis de series temporales
library(stats) # Funciones estadísticas básicas
library(forecast) # Predicción de series temporales
library(astsa) # Análisis de series temporales aplicado
library(corrplot) # Visualización de matrices de correlación
library(wordcloud) # Crear nubes de palabras
library(tidytext) # Análisis de texto con tidy data
library(AER) # Análisis econométrico con R
library(vars) # Modelos VAR y SVAR
library(dynlm) # Modelos lineales dinámicos
library(mFilter) # Filtros para series temporales
library(TSstudio) # Herramientas interactivas series temporales
library(tidyverse) # Colección de paquetes de datos tidy
library(sarima) # Modelos SARIMA
library(readr) # Leer archivos planos
library(readxl) # Leer archivos Excel
library(heatmaply) # Heatmaps interactivos
library(dplyr) # Manipulación de datos
library(ggplot2) # Sistema de gráficos
library(psych) # Procedimientos psicométricos
library(tidyr) # Reorganización de datos
library(readtext) # Leer archivos de texto
library(syuzhet) # Análisis de sentimientos
library(RColorBrewer) # Paletas de colores
library(tm) # Minería de texto
library(caret) # Entrenamiento de modelos predictivos
library(MASS) # Métodos estadísticos adicionales
library(rpart) # Modelos de partición recursiva
library(rpart.plot) # Gráficos para rpart
library(party) # Modelos basados en árboles
library(gmodels) # Herramientas de modelado
library(knitr) # Reportes dinámicos
library(cluster) # Métodos de agrupamiento
library(e1071) # Misc funciones SVM
library(pROC) # Curvas ROC
library(ISLR) # Data sets para aprendizaje estadístico
library(gridExtra) # Disposición de múltiples gráficos
library(car) # Regresión y Anova con R
library(DataExplorer) # Automatizar análisis exploratorio
library(randomForest) # Clasificación con random forest
library(class) # k-vecinos más cercanos
library(factoextra) # Visualización de resultados de clustering
library(purrr) # Programación funcional
library(viridis) # Paletas de colores para gráficos
library(scales) # Escalado de gráficos
library(lubridate) # Manipulación de fechas y horas
library(patchwork) # Combinar ggplot2 plots
library(janeaustenr) # Textos de Jane Austen
library(reshape2) # Reestructurar datos
library(tmap) # Crear mapas
library(sf) # Manipulación de datos geoespaciales
```

## Bases de Datos Necesarias
```{r message=FALSE, warning=FALSE}
setwd("../databases")

# Datos para Base Maestra Recursos Humanos
form_satisfaccion <- read_excel("form/Encuesta_Datos_FORM_Fall2023.xlsx")
form_bajas = read_csv("form/Datos_FORM_RH_FJ2024.csv")
cp_nl <- st_read("geo_reference__nl/CP_NL")

# Datos para Base Maestra Ventas
form_ventas = read_csv("form/Datos_FORM_Ventas_FJ2024.csv")
exp_vehiculos = read_csv("industry_autos_mx/exportacion_vehiculos_mx.csv")
ventas_vehiculos = read_csv("industry_autos_mx/mx_venta_vehiculos.csv")
exp_vehiculos_total = read_excel("industry_autos_mx/exportacion_vehiculos.xlsx")
```

## Transformaciones Necesarias

### FORM Bajas
```{r}
# Convertir correctamente todas las fechas desde formato numérico de Excel
form_bajas$`Fecha de nacimiento` <- as.Date(form_bajas$`Fecha de nacimiento`, origin="1899-12-30")
form_bajas$`Fecha de Alta` <- as.Date(form_bajas$`Fecha de Alta`, origin="1899-12-30")
form_bajas$`Primer Mes` <- as.Date(form_bajas$`Primer Mes`, origin="1899-12-30")
form_bajas$`Cuarto Mes` <- as.Date(form_bajas$`Cuarto Mes`, origin="1899-12-30")
form_bajas$`Fecha de Baja` <- as.Date(form_bajas$`Fecha de Baja`, origin="1899-12-30")

# Calcular la antigüedad en días y en años
form_bajas$Antiguedad_Dias <- sapply(1:nrow(form_bajas), function(i) {
  fecha_baja <- form_bajas$`Fecha de Baja`[i]
  if (is.na(fecha_baja)) {
    # Calcula la diferencia desde la fecha de alta hasta hoy si 'Fecha de Baja' es NA
    as.integer(difftime(Sys.Date(), form_bajas$`Fecha de Alta`[i], units = "days"))
  } else {
    # Calcula la diferencia entre las fechas de baja y de alta
    as.integer(difftime(fecha_baja, form_bajas$`Fecha de Alta`[i], units = "days"))
  }
})

# Calcular la antigüedad en años, usando 365.25 para incluir años bisiestos
form_bajas$Antiguedad_Años <- form_bajas$Antiguedad_Dias / 365.25

# Mostrar las primeras filas del dataframe modificado
head(form_bajas)


# Guardar el dataframe en un archivo CSV
write.csv(form_bajas, "Datos_FORM_RH_FJ2024.csv", row.names = FALSE)
```

### FORM Bajas Espacial
```{r}
form_bajas$CP <- as.character(form_bajas$CP)
cp_nl$d_codigo <- as.character(cp_nl$d_codigo)

stats_por_cp <- form_bajas %>%
  group_by(CP) %>%
  summarize(
    Conteo_Empleados = n(),
    Mediana_Antiguedad = median(Antiguedad_Dias, na.rm = TRUE),
    Mediana_Salario_Diario = median(SD, na.rm = TRUE),
    .groups = 'drop'
  )

form_bajas_espacial <- cp_nl %>%
  left_join(stats_por_cp, by = c("d_codigo" = "CP"))

# Reemplazar NA con 0 en las columnas de interés
form_bajas_espacial$Conteo_Empleados[is.na(form_bajas_espacial$Conteo_Empleados)] <- 0
form_bajas_espacial$Mediana_Antiguedad[is.na(form_bajas_espacial$Mediana_Antiguedad)] <- 0
form_bajas_espacial$Mediana_Salario_Diario[is.na(form_bajas_espacial$Mediana_Salario_Diario)] <- 0

head(form_bajas_espacial)

write_sf(form_bajas_espacial, "form_bajas_espacial.shp")
```

### FORM Satisfacción
```{r}
# Lista de columnas específicas a transformar
columnas_a_transformar <- c("salario_bueno", "prestaciones_bueno", "jornada_no_excesiva", 
                            "ofrecimiento_herramientas", "no_molestia_temperatura", "estres_bajo", 
                            "facilidad_transporte", "zona_trabajo_comoda", "permanencia_form_futuro")

# Ajustar la función para manejar el typo y valores inesperados
codificar_respuestas <- function(respuesta) {
  # Corregir posibles typos
  respuesta <- gsub("Totalmende en desacuerdo", "Totalmente en desacuerdo", respuesta)
  
  # Usar switch para asignar valores numéricos
  switch(respuesta,
         "Totalmente en desacuerdo" = 1,
         "Medianamente en desacuerdo" = 2,
         "Ni de acuerdo ni en desacuerdo" = 3,
         "Medianamente de acuerdo" = 4,
         "Totalmente de acuerdo" = 5,
         NA) # Devolver NA para cualquier respuesta no reconocida
}

# Aplicar la codificación solo a las columnas seleccionadas, asegurando que todas las transformaciones son numéricas
form_satisfaccion[columnas_a_transformar] <- lapply(form_satisfaccion[columnas_a_transformar], function(x) as.numeric(sapply(x, codificar_respuestas)))

head(form_satisfaccion)

# Guardar el dataframe en un archivo CSV
write.csv(form_satisfaccion, "Encuesta_Datos_FORM_Fall2023.csv", row.names = FALSE)
```

### FORM Factores de Venta
```{r}
form_ventas$Fecha <- as.Date(form_ventas$Fecha)

form_ventas <- form_ventas %>%
  mutate(AnoMes = floor_date(Fecha, "month"))

resumen_ventas <- form_ventas %>%
  group_by(AnoMes, `Categoría de producto`) %>%
  summarise(Cantidad_total = sum(Cantidad), .groups = 'drop')

ventas_pivot <- resumen_ventas %>%
  pivot_wider(names_from = `Categoría de producto`, values_from = Cantidad_total, values_fill = list(Cantidad_total = 0))

ventas_pivot <- ventas_pivot %>%
  arrange(AnoMes)

# Nombres de meses en español
meses_espanol <- c("enero", "febrero", "marzo", "abril", "mayo", "junio",
                   "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre")

# Asegúrate de que los nombres en 'exp_vehiculos_total$Mes' están en minúsculas o ajusta el vector a cómo estén escritos
exp_vehiculos_total$Mes <- tolower(exp_vehiculos_total$Mes)

# Convertir Año y Mes a formato de fecha
exp_vehiculos_total$Fecha <- as.Date(paste(exp_vehiculos_total$Año, match(exp_vehiculos_total$Mes, meses_espanol), "01", sep = "-"))

resumen_vehiculos <- exp_vehiculos_total %>%
  group_by(Fecha, Segmento) %>%
  summarise(Cantidad_total = sum(Cantidad), .groups = 'drop')

vehiculos_pivot <- resumen_vehiculos %>%
  pivot_wider(names_from = Segmento, values_from = Cantidad_total, values_fill = list(Cantidad_total = 0))

# Aseguramos que ambos dataframes tengan la misma granularidad de fechas
ventas_pivot <- ventas_pivot %>%
  mutate(Fecha = as.Date(paste(year(AnoMes), month(AnoMes), "01", sep = "-")))

# Combinar los dataframes
datos_combinados <- inner_join(ventas_pivot, vehiculos_pivot, by = "Fecha")

# Guardar el dataframe en un archivo CSV
write.csv(datos_combinados, "FORM_Factores.csv", row.names = FALSE)
```

